name: muslim_pro
description: "Amal â€” Namoz vaqtlari, Qibla, Tasbeh va Qur'on ilovasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Namoz vaqtlari hisobi
  adhan: ^2.0.0

  # GPS koordinatalar
  geolocator: ^13.0.2

  # Qibla yo'nalishi
  flutter_qiblah: ^3.1.0

  # Local storage
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  path: ^1.9.0

  # Tasbeh uchun tebranish
  vibration: ^2.0.0


  # API so'rovlar
  dio: ^5.7.0

  # Ruxsatlarni boshqarish
  permission_handler: ^11.3.1

  # Google Fonts
  google_fonts: ^6.2.1

  # Intl (vaqt formatlash)
  intl: ^0.19.0

  # Qur'on audio pleyer
  just_audio: ^0.10.5

  # Bildirishnomalar (namoz vaqtlari uchun)
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  flutter_localizations:
    sdk: flutter
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  fluttertoast: 8.2.10
  audioplayers: ^6.5.1
  just_audio_background: ^0.0.1-beta.17
  flutter_displaymode: ^0.7.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/data/
    - assets/audio/


  fonts:
    - family: UthmanTaha
      fonts:
        - asset: assets/fonts/uthman_taha.ttf
