name: muslim_pro
description: "Muslim Pro â€” Namoz vaqtlari, Qibla, Tasbeh va Qur'on ilovasi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Namoz vaqtlari hisobi
  adhan: ^2.0.0

  # GPS koordinatalar
  geolocator: ^13.0.2

  # Qibla yo'nalishi
  flutter_qiblah: ^3.1.0

  # Local storage
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  path: ^1.9.0

  # Tasbeh uchun tebranish
  vibration: ^2.0.0

  # Charts
  fl_chart: ^0.70.2

  # API so'rovlar
  dio: ^5.7.0

  # Ruxsatlarni boshqarish
  permission_handler: ^11.3.1

  # Google Fonts
  google_fonts: ^6.2.1

  # Intl (vaqt formatlash)
  intl: ^0.19.0

  # Qur'on audio pleyer
  just_audio: ^0.10.5

  # Bildirishnomalar (namoz vaqtlari uchun)
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  # Internet tekshirish (oflayn rejim)
  connectivity_plus: ^6.1.1
  flutter_heatmap_calendar: any
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.16.1
  share_plus: ^12.0.1
  translit: ^2.0.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  archive: ^4.0.9
  flutter_html: ^3.0.0
  quran: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: UthmanTaha
      fonts:
        - asset: assets/fonts/uthman_taha.ttf
